### ISSUE TITLE
USER STORY: Vote for best running route

### ISSUE THREAD

**Issue by matzhedman** [matzhedman/love-running#1]
In order to **have a better running experience** as a **member of the Love Running community**, I can **vote for the best running-route**

## Acceptance Criteria
* The routes are displayed in a checkbox list, one alternative is excepted.
* A Submit-button is placed in the bottom so that the user can submit and vote for a route.

## Tasks
- [ ] Add all the running routes as a list
- [ ] Create checkboxes to that list
- [ ] Create function so that one option is required, but not more than one.
