### ISSUE TITLE
USER STORY: I want to be able to vote anonymously

### ISSUE THREAD

**Issue by matzhedman** [matzhedman/love-running#2]
In order to **make my vote count** as a **member of the Love Running community**, I can **choose to vote anonymously or by having my name show**

## Acceptance Criteria
* It is optional to enter name
* A checkbox next to the name-input field that allows the user to vote with hidden identity.

## Tasks
- [ ] Create HTML and CSS for a Input field for "name"
- [ ] Add style to it so it matches the website
- [ ] Create a checkbox next to it that says "Vote anonymously"
